<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Info */
?>

<?php
$quoteAdminDate = $block->formatDate(
    $block->getQuoteAdminDate($block->getQuote()->getQuotationCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);
$quoteStoreDate = $block->formatDate(
    $block->getCreatedAtStoreDate($block->getQuote()->getStore(), $block->getQuote()->getQuotationCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);
?>

<div class="admin__page-section-item quote-information">
    <?php /* Quote Information */ ?>
    <?php if ($block->getQuote()->getProposalEmailSent()) : ?>
        <?php $email = __('The quote confirmation email was sent'); ?>
    <?php else : ?>
        <?php $email = __('The quote confirmation email is not sent'); ?>
    <?php endif; ?>

    <div class="admin__page-section-item-title">
        <span class="title">
            <?php if ($block->getNoUseQuoteLink()) : ?>
                <?php echo __('Quote # %1', $block->getQuote()->getIncrementId()) ?> (
                <span><?php echo $email ?></span>)
            <?php else : ?>
                <a href="<?php echo $block->getViewUrl($block->getQuote()->getId()) ?>">
                    <?php echo __('Quote # %1', $block->getQuote()->getIncrementId()) ?>
                </a>
                <span>(<?php echo $email ?>)</span>
            <?php endif; ?>
        </span>
    </div>
    <div class="admin__page-section-item-content">
        <table class="admin__table-secondary quote-information-table">
            <tr>
                <th><?php echo __('Quote Date') ?></th>
                <td><?php echo $quoteAdminDate ?></td>
            </tr>
            <?php if ($quoteAdminDate != $quoteStoreDate) : ?>
                <tr>
                    <th>
                        <?php echo __(
                            'Quote Date (%1)',
                            $block->getCreatedAtStoreDate(
                                $block->getQuote()->getStore(),
                                $block->getQuote()->getQuotationCreatedAt()
                            )->getTimezone()->getName()
                        ) ?>
                    </th>
                    <td><?php echo $quoteStoreDate ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <?php echo $block->getBlockHtml('quote_status') ?>
            </tr>
            <tr>
                <?php echo $block->getBlockHtml('expiry_date') ?>
            </tr>
            <tr>
                <?php echo $block->getBlockHtml('reminder_date') ?>
            </tr>
            <?php if ($block->isSingleStoreMode() == false) : ?>
                <tr>
                    <th><?php echo __('Purchased From') ?></th>
                    <td><?php echo $block->getQuoteStoreName() ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($block->getQuote()->getRelationChildId()) : ?>
                <tr>
                    <th><?php echo __('Link to the New Quote') ?></th>
                    <td>
                        <a href="<?php echo $block->getViewUrl($block->getQuote()->getRelationChildId()) ?>">
                            <?php echo $block->getQuote()->getRelationChildRealId() ?>
                        </a>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($block->getQuote()->getRelationParentId()) : ?>
                <tr>
                    <th><?php echo __('Link to the Previous Quote') ?></th>
                    <td>
                        <a href="<?php echo $block->getViewUrl($block->getQuote()->getRelationParentId()) ?>">
                            <?php echo $block->getQuote()->getRelationParentRealId() ?>
                        </a>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($block->getQuote()->getRemoteIp() && $block->shouldDisplayCustomerIp()) : ?>
                <tr>
                    <th><?php echo __('Placed from IP') ?></th>
                    <td>
                        <?php echo $block->getQuote()->getRemoteIp(); ?>
                        <?php if ($block->getQuote()->getXForwardedFor()) : ?>
                            <?php $xForwarderFor = ' ('
                                . $block->escapeHtml($block->getQuote()->getXForwardedFor())
                                . ')'; ?>
                        <?php else : ?>
                            <?php $xForwarderFor = ''; ?>
                        <?php endif; ?>
                        <?php echo $xForwarderFor; ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($block->getQuote()->getGlobalCurrencyCode() != $block->getQuote()->getBaseCurrencyCode()) : ?>
                <tr>
                    <th>
                        <?php echo __(
                            '%1 / %2 rate:',
                            $block->getQuote()->getGlobalCurrencyCode(),
                            $block->getQuote()->getBaseCurrencyCode()
                        ) ?>
                    </th>
                    <td><?php echo $block->getQuote()->getBaseToGlobalRate() ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($block->getQuote()->getBaseCurrencyCode() != $block->getQuote()->getQuoteCurrencyCode()) : ?>
                <tr>
                    <th>
                        <?php echo __(
                            '%1 / %2 rate:',
                            $block->getQuote()->getQuoteCurrencyCode(),
                            $block->getQuote()->getBaseCurrencyCode()
                        ) ?>
                    </th>
                    <th><?php echo $block->getQuote()->getBaseToQuoteRate() ?></th>
                </tr>
            <?php endif; ?>
            <?php echo $block->getChildHtml('quote_details_quote_select_rate'); ?>
        </table>
    </div>
</div>