<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var \Cart2Quote\Quotation\Block\Quote\Email\Items\Quote\Column $block */

?>
<?php 
$productId = $block->getItem()->getProductId();
$objectManagerHere = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManagerHere->get('Magento\Catalog\Model\Product')->load($productId);
$productImage = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'category_page_list', array('height' => '135' , 'width'=> '135'))->getUrl();
?>
<td class="item-info<?php if ($block->getItemOptions()) : ?> has-extra<?php endif; ?>" colspan="2">
    <strong class="product-name"><?php echo $block->escapeHtml($block->getItem()->getName()) ?></strong>
    <p class="sku"><?php echo __('SKU'); ?>: <?php echo $block->escapeHtml($block->getSku($block->getItem())) ?></p>
    <?php if ($block->getItemOptions()) : ?>
        <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option) : ?>
                <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
                <dd>
                    <?php echo nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
    <?php if ($addInfoBlock) : ?>
        <?php echo $addInfoBlock->setItem($block->getItem())->toHtml() ?>
    <?php endif; ?>
</td>
<td> 
 <p class="sku">
               <img height="100" width="100" src="<?= $productImage ?>" alt="<?= __('Product Image');?>">
            </p>
</td>

