<?php
/**
 * Copyright © 2015 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 *
 * Magenest_ZohocrmIntegration extension
 * NOTICE OF LICENSE
 *
 * @category  Magenest
 * @package   Magenest_ZohocrmIntegration
 * @author ThaoPV
 */
?>
<div class="actions actions-get-auth-token">
    <div id="auth_token_result" class="message-validation hide"></div>
    <button  class="action-validate-get-auth-token" type="button"  id="<?php echo $block->getHtmlId() ?>">
        <span><?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script>
    require(['jquery'], function(jQuery){
        jQuery('.action-validate-get-auth-token').click(function(){
            var username = jQuery('#zohocrm_config_email').val();
            var password = jQuery('#zohocrm_config_passwd').val();
            var data = {
                username: username,
                password : password,
                form_key: FORM_KEY
            };
            var url = '<?php echo $block->getUrl('zohocrm/system_config_getauth/getAuth'); ?>//';
            jQuery.ajax({
                type: "POST",
                url: url,
                data: data,
                showLoader: true,
                success: function(response){
                    var result_token = jQuery('#auth_token_result');
                    var responseObj = JSON.parse(response);
                    console.log(responseObj);
                    if(responseObj.error == 1){
                        result_token.removeClass('hide').addClass('error');
                        result_token.html(responseObj.description);
                    }else{
                        jQuery('#zohocrm_config_auth_token').val(responseObj.description);
                        jQuery('#<?php echo $block->getHtmlId() ?>').attr('disabled', 'disabled');
                        result_token.removeClass('hide').addClass('success');
                        result_token.html('Get Access Token Success');
                    }
                }
            });
        });
    });
</script>