<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
$rfqHelper       = $this->helper('Lof\RequestForQuote\Helper\Data');
$enable_price             = $rfqHelper->getConfig("general/enable_price");
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" style="width:100%;border:1px solid #E8E6E7;" cellspacing="0" cellpadding="15">
        
        <thead style="color:#353132;padding:10px;text-align:left;background:#fff;">
            <tr>
                <th class="item-info h" style="padding-left:15px;">
                    <?= /* @escapeNotVerified */  __('ITEM'); ?>
                </th>
				<?php if($enable_price) { ?>
                <th class="item-price">
                    <?= /* @escapeNotVerified */  __('PRICE'); ?>
                </th>
                <?php } ?>
                <th class="item-qty">
                    <?= /* @escapeNotVerified */  __('QTY'); ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php
            if ($_item->getParentItem()) {
                continue;
            }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    
    </table>
    <?php if($enable_price) { ?>
        <table class="order-totals" style="width:100%;">
            <tr>
                <td style="width:60%;padding-right:15px;">
					<div class="general_term">
						<div class="terms" style="margin-top: 25px; color: #687176; border: 1px solid #cccccc;padding: 15px;border-radius: 20px;background: #f5f5f5;"> <span class="term-title" style="font-size: 14px;font-weight: 600;margin: 25px;"> General Terms &amp; Conditions </span>
						<ul style=" padding-left: 10px;padding-top: 15px;">
							<li style="font-size: 11px;">All products are designed and assembled in the USA</li>
							<li style="font-size: 11px;">Price quote is good for 90 days from creation date</li>
							<li style="font-size: 11px;">Lifetime Warranty on all products</li>
							<li style="font-size: 11px;">Payment Terms: Wire Transfer, Credit Card, Check, Net 30</li>
						</ul>
						</div>
					</div>
                </td>
                <td colspan="2">
                    <table cellpadding="10" style="width:100%; border:1px solid #E8E6E7;margin-top:10px;  border-collapse: collapse; !important;">
						<thead>
							<tr style="border-bottom:1px solid #000">
								<th colspan="3"  style="    border-bottom: 1px solid #e8e6e7; width:100%; font-size: 21px;font-weight: 400;">Quote Summary</th>
							</tr>
						</thead>
                        <?= $block->getChildHtml('order_totals') ?>
                    </table>
                </td>
            </tr>
        </table>
    <?php } ?>
<?php endif; ?>
