<br/>
    <div class="quote-totals-actions">
        <div class="actions">
            <button id="quote-pdf" title="<?php echo __("Preview Quote PDF");?>" type="button" class="action-default scalable action-default scalable" onclick="location.href='<?php echo $this->getPreviewPdfUrl();?>'" data-ui-id="widget-button-13">
            <span><?php echo __("Preview Quote PDF");?></span>
            </button>
        </div>
    </div>