<style>
	.quote-page-content input.form-control {
		font-size: 1em;
		display: block;
		width: 100%;
		height: auto;
		box-sizing: border-box;
		color: inherit;
		margin-bottom: 1em;
		padding: 1em;
		background-color: #ffffff;
		border: 1px solid #cecece;
		appearance: none;
		border-radius: 2px;
		box-shadow: 0 0 5px #dddddd;
}
	.quote-page-content input[type="submit"] {
		width: 340px;
		background: #F7921E;
		border-color: #F7921E;
		font-weight: bold;
		text-transform: uppercase;
		font-size: 15px;
		color: #fff;
}
	.quote-page-content input[type="submit"]:hover{
			background-color:#696969;
			border-color: #696969;
	}
	.quote-page-content select.form-control {
		float: none;
		width: 100%;
		height: 44px;
		margin-bottom: 1em;
		padding: 1em;
}
	.quote-page-content textarea {
		height: 200px;
		resize: vertical;
		margin-bottom: 1em;
}
	.quote-page-content .form-cc.center {
		text-align: center !important;
}
.quote-page-content .form-cc.center input {
		display: inline-block;
}
</style>
<div class="quote-page-content">
	<form action="<?php echo $block->getBaseUrl().'appsyscoquoteform/index/quote/'; ?>" method="post">
		<div class="col-md-12">
			<div class="col-md-6 float-left">
				<div class="form-group form-cc">
				    <label for="first_name" style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">First Name</label>
					<input name="first_name" id="first_name" class="form-control" placeholder="First Name" type="text" required>
				</div>
			</div>
			<div class="col-md-6 float-left">
				<div class="form-group form-cc">
					<label for="last_name" style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">Last Name</label>
					<input name="last_name" id="last_name" class="form-control" placeholder="Last Name" type="text" required>
				</div>
			</div>
			<div class="col-md-6 float-left">
				<div class="form-group form-cc">
					<label for="telephone" style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">Telephone</label>
					<input name="telephone" id="telephone" class="form-control" placeholder="Telephone" type="text" required>
				</div>
			</div>
			<div class="col-md-6 float-left">
				<div class="form-group form-cc">
					<label for="email" style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">Email</label>
					<input id="email" name="email" class="form-control" placeholder="Email" type="email" required>
				</div>
			</div>
			<div class="col-md-12 float-left">
				<div class="form-group form-cc">
					<label for="comment" style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">Notes</label>
					<textarea  id="comment" name="comment" class="form-control" placeholder="Notes" type="text" required></textarea>
				</div>
			</div>
			<div class="col-md-6 float-left">
				<div class="form-group form-cc">
					<label for="industry_name" style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">Industry Name</label>
					<select id="industry_name" name="industry_name" class="form-control" required>
                            <option value="" disabled selected>What industry are you in?</option>
							<option value="Advertising">Advertising</option>
							<option value="Agriculture">Agriculture</option>
							<option value="Apparel">Apparel</option>
							<option value="Architecture">Architecture</option>
							<option value="Banking/Financial/Investment">Banking/Financial/Investment</option>
							<option value="Chiropractic">Chiropractic</option>
							<option value="Construction">Construction</option>
							<option value="Education">Education</option>
							<option value="Food Service">Food Service</option>
							<option value="Government">Government</option>
							<option value="Healthcare">Healthcare</option>
							<option value="Hospitality">Hospitality</option>
							<option value="Insurance">Insurance</option>
							<option value="Legal">Legal</option>
							<option value="Manufacturing">Manufacturing</option> 
							<option value="Media/Broadcasting">Media/Broadcasting</option>
							<option value="Non-Profit">Non-Profit</option>
							<option value="Pharmaceutical">Pharmaceutical</option>
							<option value="Professional Services">Professional Services</option>
							<option value="Real Estate">Real Estate</option>
							<option value="Retail">Retail</option>
							<option value="Technology">Technology</option>
							<option value="Telecommunications">Telecommunications</option>
							<option value="Transport">Transport</option>
							<option value="Other">Other</option>
                    </select>
				</div>
			</div>
			<div class="col-md-6 float-left">
				<div class="form-group form-cc">
					<label for="hear_about" style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">Hear About</label>
					<select id="hear_about" name="hear_about" class="form-control" required>
                            <option value="" disabled selected>How Did You Hear About Us?</option>
                            <option value="Google Search">Google Search</option>
							<option value="Bing Search">Bing Search</option>
							<option value="Word of Mouth">Word of Mouth</option>
							<option value="Print">Print</option>
							<option value="Video">Video</option>
							<option value="Article/Blog">Article/Blog</option>
							<option value="Social Media">Social Media</option>
							<option value="Return Customer">Return Customer</option>
							<option value="Other">Other</option>
                    </select>
				</div>
			</div>
			<div class="col-md-6 float-left">
				<div class="form-group form-cc">
					<label for="business_type" style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">Business Type</label>
					<select id="business_type" name="business_type" class="form-control" required>
                        <option value="" disabled selected>Type?</option>
                        <option value="Large Office Purchasing Manager">Large Office Purchasing Manager</option>
						<option value="Small Business Owner/Office Manager">Small Business Owner/Office Manager</option>
						<option value="Home Office">Home Office</option>
                    </select>
				</div>
			</div>
			<div class="col-md-12 float-left">
				<div class="form-group form-cc center">
					<input type="submit" class="form-control" value="Submit">
				</div>
			</div>
		</div>
	</form>
</div>