<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Magento\Catalog\Block\Product\View */
/** @var $quoteButton \Cart2Quote\Quotation\Block\Button */
?>
<?php $quoteButton = $block->addChild('quote_button', 'Cart2Quote\Quotation\Block\Button'); ?>
<?php $_product = $block->getProduct(); ?>
<?php $cartButtonTitle = __('Add to Cart'); ?>
<?php $quoteButtonTitle = __('Add to Quote'); ?>
<?php $validators = $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>

<?php if ($_product->isSaleable() || $quoteButton->showQuoteButton()) : ?>
    <div class="box-tocart aaa">
        <fieldset class="fieldset">

            <?php if ($block->shouldRenderQuantity()) : ?>
                <!-- Qty start -->
                <div class="field qty">
                    <label class="label" for="qty"><span><?php echo __('QUANTITY: ') ?></span></label>

                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $validators ?>"
                        />
                    </div>
					<div class="qty-changer">
                        <a href="javascript:void(0)" class="qty-inc"><i class="porto-icon-up-dir"></i><span style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">increase</span></a>
                        <a href="javascript:void(0)" class="qty-dec"><i class="porto-icon-down-dir"></i><span style="border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; word-wrap: normal !important;">decrease</span></a>
                    </div>
                </div>
                <!-- Qty stop -->
            <?php endif; ?>

            <div class="actions">

                <?php if ($_product->isSaleable()) : ?>
                    <!-- Cart button start -->
                    <button type="submit"
					        data-name="<?php echo $_product->getName() ?>"
                            title="<?php echo $cartButtonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php echo $cartButtonTitle ?></span>
                    </button>
                    <!-- Cart button stop -->
                <?php endif; ?>

               <!-- <?php if ($quoteButton->showQuoteButton() && !$quoteButton->showMessageNotLoggedIn()) : ?>
                    <button type="submit"
                            title="<?php echo $quoteButtonTitle ?>"
                            class="action tocart"
                            id="product-addtoquote-button">
                        <span><?php echo $quoteButtonTitle ?></span>
                    </button>
                <?php elseif ($quoteButton->showMessageNotLoggedIn()) : ?>
                    <button id="product-addtoquote-button" disabled="disabled" class="action tocart">
                        <span><?php echo __('Please login to add to Quote.'); ?></span>
                    </button>
                <?php endif; ?> -->

                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
<?php endif; ?>
<div id="addtocart_modal"  class="modalDialog" style="display: none;"></div>

<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script>
	    
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Cart2Quote_Quotation/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            var addToQuote = false;
            $('#product-addtoquote-button').click(function (e) {
                addToQuote = "<?php echo $block->getUrl('quotation/quote/add')?>";
            });

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).quotationAddToCart({
                        quoteFormUrl: addToQuote,
                        bindSubmit: false,
                        noAjax: false
                    });

                    widget.quotationAddToCart('submitForm', $(form));
                    addToQuote = false;
                    return false;
                }
            });
        });
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Cart2Quote_Quotation/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            var addToQuote = false;
            $('#product-addtoquote-button').click(function (e) {
				addToQuote = "<?php echo $block->getUrl('quotation/quote/add') ?>";
            });
			
			
			$('#product-addtocart-button').click(function () {
				
				
				
				
				var cartUrl = "<?php echo $block->getUrl('checkout/cart') ?>";
                    var modal_options = {
                    type: 'popup',
                    buttons: [
                        {
                            text: "Continue shopping",
                            class: 'primary btn-lg btn-info addtocart_modal_continue',
                            click: function () {
                            this.closeModal();
                            return false;
                            }
                        },                        
                        {
                            text: "View and edit cart",
                            class: 'primary btn-lg btn-success addtocart_modal_gotocart',
                            click: function () {
                            location.href = cartUrl;
                            return false;
                            }
                        }
                    ]
                    };

                    var popup = $('#addtocart_modal');
                    var product_name = $('#product_addtocart_form').find("button").data("name");

                    // reset modal content every time
                    popup.html(""); 
                    popup.append("<div class='confirm-text'>The product <strong>" + product_name + "</strong> is added to your shopping cart.</div>");
                    popup.modal(modal_options);
                   popup.modal('openModal');
				});
			

            $('#product_addtocart_form').mage('validation',{
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).quotationAddToCart({
                        quoteFormUrl: addToQuote,
                        bindSubmit: false
                    });
					widget.quotationAddToCart('submitForm', $(form));
                    addToQuote = false;
                    return false;
                }
            });
			
    $("body").click
	(
    function(e)
    {
		var checkclass = e.target.className ;  
		if (checkclass.indexOf("_show") >= 0){

		$( ".action-close" ).trigger( "click" );
		}
    
    }
    );
	
	 });
    </script>
<?php endif; ?>
