<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>

<div class="quote-date date-zone"><?php echo __(
        '<span class="label">Quote Request Date:</span> %1',
        '<date>' . $block->formatDate(
            $block->getQuote()->getQuotationCreatedAt(),
            \IntlDateFormatter::LONG
        ) . '</date>'
    ) ?></div>
<?php if ($block->getQuote()->getExpiryEnabled()): ?>
    <div class="quote-expiry-date date-zone"><?php echo __(
            '<span class="label">Proposal Valid Until:</span> %1',
            '<date>' . $block->formatDate(
                $block->getQuote()->getExpiryDate(),
                \IntlDateFormatter::LONG
            ) . '</date>'
        ) ?></div>
<?php endif; ?>
<?php $_note = $block->getQuote()->getCustomerNote(); ?>
<?php if (isset($_note)) : ?>
    <div class="block block-order-details-view">
        <strong class="box-title"><span><?php echo __('Remarks with proposal') ?></span></strong>

        <div class="block-content">
            <div class="box box-quote-remarks">
                <div class="box-content">
                    <?php echo $_note; ?>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>
