<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */
?>
<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildren()); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($_item->getOptions() || $parentItem->getDescription()): ?>
        <?php $_showlastRow = true ?>
    <?php else: ?>
        <?php $_showlastRow = false ?>
    <?php endif; ?>

    <?php if ($_item->getParentItem()): ?>
        <tr class="options-label options-label-header">
            <?php $attributes = json_decode($_item->getOptionByCode('bundle_selection_attributes')->getValue(),
                true); ?>
            <td class="col label" colspan="2"><?php echo $attributes['option_label']; ?></td>
        </tr>
    <?php endif; ?>
    <tr id="order-item-row-<?php echo $_item->getItemId() ?>"
        class="<?php if ($_item->getParentItem()): ?>item-options-container<?php else: ?>item-parent<?php endif; ?>"<?php if ($_item->getParentItem()): ?> data-th="<?php echo $_item->getName() ?>"<?php endif; ?>>
        <?php if (!$_item->getParentItem()): ?>
            <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                <strong class="product name product-item-name"><?php echo $_item->getName() ?></strong>
                <p class="sku"><?= __('SKU'); ?>: <?php echo $block->escapeHtml($_item->getSku()) ?></p>
            </td>
        <?php else: ?>
            <td class="col value value-padding" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                <?php echo $block->escapeHtml($_item->getQty() . ' x ' . $_item->getName()) ?>
            </td>
        <?php endif; ?>
        <td class="item-qty" data-th="<?php echo $block->escapeHtml(__('Quantity')); ?>">
            <?php if (!$_item->getParentItem()): ?>
                <?php echo $_item->getQty(); ?>
            <?php endif; ?>
        </td>
    </tr>
    <?php if ($_item->getDescription()) : ?>
        <tr>
            <td class="item-comment">
                <div class="item-comment-container">
                    <span class="product-name"><?= __('Comment'); ?></span>
                    <?php echo $_item->getDescription(); ?>
                </div>
            </td>
            <td></td>
        </tr>
    <?php endif; ?>
<?php endforeach; ?>
