<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue("web/unsecure/base_url");
?>
<?php /** @var $block \Cart2Quote\Quotation\Block\Quote\Success */ ?>
<div class="quotation-success">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cart2quote_success_page_content')->toHtml();?>

    <?php echo $block->getAdditionalInfoHtml() ?>
    
	
	<div class="actions-toolbar" style="width: 25%;float: left;">
        <div class="primary">
            <a class="action primary continue" title="<?php echo __('GO TO MY ACCOUNT') ?>"
               href="<?php echo $conf.'customer/account/'; ?>"><span><?php echo __('GO TO MY ACCOUNT') ?></span></a>
        </div>
    </div>
	<div class="actions-toolbar" style="width: 25%;float: left;">
        <div class="primary">
            <a class="action primary continue" title="<?php echo __('Continue Shopping') ?>"
               href="<?php echo $block->getUrl() ?>"><span><?php echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
